name: deep-nebulae
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libnsl=2.0.1
  - libsqlite=3.47.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.10.15
  - readline=8.2
  - setuptools=75.6.0
  - tk=8.6.13
  - tzdata=2024b
  - wheel=0.45.1
  - xz=5.2.6
  - pip:
    - contourpy==1.3.1
    - cycler==0.12.1
    - filelock==3.13.1
    - fonttools==4.55.0
    - fsspec==2024.2.0
    - imageio==2.36.0
    - jinja2==3.1.3
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - markupsafe==2.1.5
    - matplotlib==3.9.2
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==1.26.3
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.21.5
    - nvidia-nvtx-cu11==11.8.86
    - packaging==24.2
    - pillow==10.2.0
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - scikit-image==0.24.0
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - six==1.16.0
    - sympy==1.13.1
    - threadpoolctl==3.5.0
    - tifffile==2024.9.20
    - torch==2.5.1+cu118
    - torchvision==0.20.1+cu118
    - triton==3.1.0
    - typing-extensions==4.9.0
